### ISSUE TITLE
error: failed retrieving file 'nuvolaplayer.db' from repo.celti.name

### ISSUE THREAD

**Issue by marek287** [tiliado/nuvola-arch-packaging#4]
I'm getting this error for some time: 
error: failed retrieving file 'nuvolaplayer.db' from repo.celti.name : The requested URL returned error: 404

**Comment by jiri-janousek** [comment]
Hello @marek287. The repository is currently unmaintained as @Celti cannot work on it because of life difficulties. I'll update README to avoid further confusion.

**Comment by jamesan** [comment]
Yes, the repo's database file is missing as can be seen here: https://repo.celti.name/archlinux

@fenryxo: the ArchWiki article on unofficial listing that includes this repo should also be updated at: https://wiki.archlinux.org/index.php/Unofficial_user_repositories#nuvolaplayer

**Comment by jiri-janousek** [comment]
> the ArchWiki article on unofficial listing that includes this repo should also be updated at: https://wiki.archlinux.org/index.php/Unofficial_user_repositories#nuvolaplayer

Feel free to remove Nuvola Player from that page. I don't have an account there.

**Comment by jiri-janousek** [comment]
README & wiki page updated; repository archived
