### ISSUE TITLE
Nuvolaplayer is not in archlinux repository anymore

### ISSUE THREAD

**Issue by WhippetsAintDogs** [tiliado/nuvola-arch-packaging#5]
There's only celti-extra - no nuvolaplayer...

**Comment by jiri-janousek** [comment]
Hello @WhippetsAintDogs. The repository has been discontinued by its maintainer. [Nuvola Player plans to officially support Arch Linux by providing cross-distribution packages](https://medium.com/nuvola-news/nuvola-player-and-plans-for-2017-49afd12f23ae#.qnvy25ety). Meanwhile, you can use Arch Linux AUR to install Nuvola Player. However, the AUR packages are not maintained by the Nuvola Player team.
